services:
  db:
    image: mysql:8.0
    container_name: mi-mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: tatuajes_db
      MYSQL_ROOT_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata
